### ISSUE TITLE
Sample input file?

### ISSUE THREAD

**Issue by ppbrown** [StudistCorporation/fluent-plugin-timestream#21]
Hi,
I'm not a ruby programmer, so I'm having difficulty following the "test" code.
Could you maybe just provide a simple json file, that people could pass to "fluent-cat", to verify that the plugin is working?

**Comment by mtakeda15** [comment]
Hi @ppbrown,

I've never used fluent-cat, but this json written in [sample config file](https://github.com/StudistCorporation/fluent-plugin-timestream/blob/main/fluent.conf.sample) is simple json example.

`{"key": "value", "time":1620000000.123456789}`

Other examples:
`{"dimension1": "val1", "dimension2": "val2", "time":1680653042}`
`{"dimension1": "val1", "measureXXX": "measureValue", "time":"2023-04-05T00:04:02.123456Z"}`

**Comment by ppbrown** [comment]
Unfortunately I did not understand those examples.
Perhaps It's best if I just describe what I want to happen and you can suggest what to do?

I should say that I am new to timestream. So right now, I'm at the testing level.
I thought i should be able to create and fill a trivial timestream table with single column data.
So my desired input stream woud look something like

```
{"message":"first message"}
{"message":"second message"}

```

Since I am "measuring" the value of 'message' over time, I would think I should put in the plugin config,

```
<measure>
   name "message"
   type "VARCHAR"
 </measure>
  ```
  
  However, that does not work. The plugin complains about "record has no dimensions."
  
  
  Oddly, if I change my input to be
  
  `'{"extrafield":"blah", "message":"more"}'`
  
  THEN it works.
  
  If this is expected behavior, and it is required to pass in a value for the "measure", PLUS some other value...
  it would be nice to update the plugin's error message for new folks like me, to make that clearer.
  I dont understand what "dimension" means. I just want to shove my data through :)
  
  People who have used fluentd in other capacities, are expecting this kind of behavior. They are expecting to be able to use
  `{"message": "This is a debug line"}`
  
  and have it go through.

**Comment by ppbrown** [comment]
if I look atthe AWS concepts page, it describes,

> Dimension - An attribute that describes the meta-data of a time series. A dimension consists of a dimension name and a dimension value.

But metadata should be **optional** in my opinion. It shouldnt be required.
So the complaint about no dimentions, doesnt make sense to me

**Comment by ppbrown** [comment]
PS: you said you hadnt used fluent-cat, so here's a specific example


`echo '{"message": "This is a debug line"}' | fluent-cat sample.log`

**Comment by valerauko** [comment]
>But metadata should be optional in my opinion. It shouldnt be required.

While your point is valid, the requirement of at least one dimension is enforced by the Timestream AWS SDK itself. It throws a Aws::TimestreamWrite::Errors::ValidationException with the message "At least one dimension is required for a record".

**Comment by mtakeda15** [comment]
This plugin uses aws-sdk-timestreamwrite(official ruby sdk), and It doesn't permit to send record without dimension.
for example, if I send a record without dimension, it raises the Error below:

`Aws::TimestreamWrite::Errors::ValidationException: At least one dimension is required for a record.`

Therefore, this plugin ignores record when it has no dimensions.
This is also noted in the Readme.

> The plugin ignores record when it has no dimensions.

I only know this document refers the restriction.
It is Japanese document, but says "A record is consists of at least one dimension, timestamp, and measure"
https://d1.awsstatic.com/webinars/jp/pdf/services/20201216_BlackBelt_AmazonTimestream.pdf
